[build]
  command = "npm install"
  publish = "."

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/server.js"
  status = 200

[functions]
  directory = "."
  node_bundler = "esbuild" 