services:
  - type: web
    name: mgjc-enfants
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true
    # Ajout de configurations pour éviter les timeouts
    maxConcurrency: 1
    # Configuration pour les fichiers statiques
    staticPublishPath: . 